"""add webhook delivery

Revision ID: 2be820bcdfd1
Revises: 5f0a2c9e7b31
Create Date: 2026-10-03 13:31:19.435263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be820bcdfd1'
down_revision: Union[str, Sequence[str], None] = '5f0a2c9e7b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_delivery',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('request_body', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delivery_retry', 'webhook_delivery', ['status', 'next_retry_at'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_instance_id'), 'webhook_delivery', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_delivery_instance_id'), table_name='webhook_delivery')
    op.drop_index('idx_delivery_retry', table_name='webhook_delivery')
    op.drop_table('webhook_delivery')
    # ### end Alembic commands ###
