"""add instance tables

Revision ID: 49524dde24ae
Revises: a7b5bb401ea8
Create Date: 2026-10-03 12:36:08.534942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49524dde24ae'
down_revision: Union[str, Sequence[str], None] = 'a7b5bb401ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_event',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('operation_id', sa.String(length=64), nullable=True),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_inst_time', 'instance_event', ['instance_id', 'created_at'], unique=False)
    op.create_index('idx_outbox', 'instance_event', ['dispatched', 'created_at'], unique=False)
    op.create_table('workflow_instance',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('definition_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('definition_version', sa.Integer(), nullable=False),
    sa.Column('business_key', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('initiator_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_node_keys', sa.JSON(), nullable=False),
    sa.Column('engine_state', sa.JSON(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('start_form_snapshot', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_initiator_status', 'workflow_instance', ['initiator_id', 'status', 'started_at'], unique=False)
    op.create_index('uk_business', 'workflow_instance', ['definition_id', 'tenant_id', 'business_key'], unique=True, sqlite_where=sa.text('business_key IS NOT NULL'), postgresql_where=sa.text('business_key IS NOT NULL'))
    op.create_table('workflow_instance_task',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('instance_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('node_name', sa.String(length=128), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.String(length=64), nullable=False),
    sa.Column('assignee_source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=True),
    sa.Column('counter_sign_group_id', sa.String(length=64), nullable=True),
    sa.Column('form_snapshot', sa.JSON(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignee_status', 'workflow_instance_task', ['assignee_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_task_instance', 'workflow_instance_task', ['instance_id'], unique=False)
    op.create_table('workflow_variable',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('instance_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'scope', 'key', name='uk_var')
    )
    op.create_table('task_opinion',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('task_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('author_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['workflow_instance_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_opinion_instance', 'task_opinion', ['instance_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_task_opinion_instance_id'), 'task_opinion', ['instance_id'], unique=False)
    op.create_table('task_substitute',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('task_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('from_user_id', sa.String(length=64), nullable=False),
    sa.Column('to_user_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.Column('effective', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['workflow_instance_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_substitute')
    op.drop_index(op.f('ix_task_opinion_instance_id'), table_name='task_opinion')
    op.drop_index('idx_opinion_instance', table_name='task_opinion')
    op.drop_table('task_opinion')
    op.drop_table('workflow_variable')
    op.drop_index('idx_task_instance', table_name='workflow_instance_task')
    op.drop_index('idx_assignee_status', table_name='workflow_instance_task')
    op.drop_table('workflow_instance_task')
    op.drop_index('uk_business', table_name='workflow_instance', sqlite_where=sa.text('business_key IS NOT NULL'), postgresql_where=sa.text('business_key IS NOT NULL'))
    op.drop_index('idx_initiator_status', table_name='workflow_instance')
    op.drop_table('workflow_instance')
    op.drop_index('idx_outbox', table_name='instance_event')
    op.drop_index('idx_event_inst_time', table_name='instance_event')
    op.drop_table('instance_event')
    # ### end Alembic commands ###
