"""create definition tables

Revision ID: a7b5bb401ea8
Revises: 
Create Date: 2026-10-03 12:02:25.600534

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7b5bb401ea8'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definition',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definition_category'), 'workflow_definition', ['category'], unique=False)
    op.create_index(op.f('ix_workflow_definition_code'), 'workflow_definition', ['code'], unique=True)
    op.create_table('workflow_definition_version',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('definition_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('dsl', sa.JSON(), nullable=False),
    sa.Column('dsl_hash', sa.String(length=64), nullable=False),
    sa.Column('form_schema', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_id', 'version', name='uk_def_version')
    )
    op.create_index(op.f('ix_workflow_definition_version_definition_id'), 'workflow_definition_version', ['definition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_definition_version_definition_id'), table_name='workflow_definition_version')
    op.drop_table('workflow_definition_version')
    op.drop_index(op.f('ix_workflow_definition_code'), table_name='workflow_definition')
    op.drop_index(op.f('ix_workflow_definition_category'), table_name='workflow_definition')
    op.drop_table('workflow_definition')
    # ### end Alembic commands ###
